language: java
install: true

script:
  - ./gradlew clean test
  - ./gradlew clean test -PcontractsVersion=2.1.0.RELEASE

env:
- CI=true

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/