language: java
install: true

script:
  - ./gradlew clean test -d
  - ./gradlew clean test -PcontractsVersion=2.1.0.RELEASE -d

env:
- CI=true

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
